### ISSUE TITLE
Make sections linkable

### ISSUE THREAD

**Issue by yndajas** [fishpercolator/name.pn#102]
**Is your feature request related to a problem? Please describe.**
Currently you can only link to your profile/the page as a whole

**Describe the solution you'd like**
I'd like to be able to link directly to the pronunciation section and the pronouns section in different places, e.g. by using IDs on each `.card` and ideally on each `profile-card__heading`

**Comment by pedantic-git** [comment]
Thanks for this suggestion! It's easy to implement the way you suggest but would you mind elaborating more about your use case so I can be sure to implement the best solution for what you're trying to achieve?

**Comment by yndajas** [comment]
Yep! I've just pushed some code so you can see an example: https://github.com/yndajas/simple-website/commit/c6afe772a54b0bf283055429a58fa740f2f62e3c. (I'm working on building a much simpler personal website than the ones I've given up building/maintaining in the past!)

Happy to have a look at coding a solution for this over the weekend, or leave it to you to do whenever!

**Comment by pedantic-git** [comment]
With this in mind, would you prefer to have specific URLs for the pronunciation and pronouns that _only_ show these details, or highlight them in some way? I'm conscious that linking to page fragments is often considered poor/confusing user experience. It would be easy to add them in the meantime, of course!

**Comment by yndajas** [comment]
That could be even better! I quite like the idea of highlighting (ideally without JavaScript), but specific pages for particular sections or individual datapoints with a link back to the full profile would also be very nice

**Comment by pedantic-git** [comment]
Cool - thank you for this input! I'll give it some thought and probably deliver it in multiple stages. I agree about no JS here - totally not needed! The UI is based on turbolinks right now so it uses JS for smooth transitions between pages/views but it's just for visual effect and the views are functional without it.

**Comment by pedantic-git** [comment]
@yndajas I've made a first pass at this behaviour and deployed it to QA - see https://name-pn-qa.herokuapp.com/quinn-daley for an example. Clicking the link icon will generate a link to a specific point on the page which is a scroll-to-fragment  if JS is disabled, but on JS browsers it hides all the other sections and reveals a link to show them all again.

What do you think? Does this meet your use case? How is the user experience?

**Comment by pedantic-git** [comment]
@yndajas This is live on production now - let me know if it works for your use case! https://name.pn/ynda-jas#pronunciation https://name.pn/ynda-jas#pronouns
