### ISSUE TITLE
"Any pronouns are fine"

### ISSUE THREAD

**Issue by pedantic-git** [fishpercolator/name.pn#19]
At the moment, name.pn forces people to select at least one pronoun set. This is to ensure that cis people, who often don't think much about their own pronouns, fill out the profile appropriately in order to avoid othering trans and non-binary people with their carefully prepared profiles that do include pronouns.

But some people genuinely are happy to have any pronouns used for them, so this should probably be included as an option.

But the question is, how do we allow this as an option without having it be abused by cis people who are trying to avoid including their pronouns on their profile because they "disagree with the concept" or whatever? One possibility is showing random pronoun examples on the user's page, or showing all of he/she/they at all times.

I'm interested to hear some perspectives on what this would look like before implementing. If you are an "any pronouns are fine" person, how would you like to see this implemented?

**Comment by kimadactyl** [comment]
I think random is good, esp as "all" would presumably extend to neopronouns too?
