### ISSUE TITLE
No / unclear pronouns

### ISSUE THREAD

**Issue by pedantic-git** [fishpercolator/name.pn#20]
Some people have no pronouns, either because none fit or because they are still trying to work out what the right pronouns for are for themself.

name.pn should offer an option for "no pronouns" which puts the user's name in all the pronoun usage examples.

Like with #19 I'm worried about this being abused by cis people who "disagree with the concept" so I'm keen to hear from people who really do have no (or unknown/unclear) pronouns on how this feature should be implemented.

**Comment by kimadactyl** [comment]
I think if people want to abuse the platform its very unlikely they would do it using an arbritrary feature :)

**Comment by pedantic-git** [comment]
@kimadactyl Yeah, I guess "abuse" is the wrong word here. I suppose I'm trying to avoid a situation where cis people can feel comfortable leaving their pronouns field blank, because it runs the risk of "othering" queer and trans users of the platform. I'm almost certainly overthinking it though!

**Comment by kimadactyl** [comment]
I think so yeah and in general I don't think you need to be overly defensive about people using it a certain way. Using the site _at all_ is an improvement, using it "properly" is an improvement on that, etc. Always slightly better :)

**Comment by pedantic-git** [comment]
This and #19 are starting to take shape in the branch [pronounless](https://github.com/fishpercolator/name.pn/tree/pronounless).

An interesting challenge is how to do the reflexive when someone has no pronouns - it works differently depending on context:

* "Abby invented this recipe herself" -> "Abby invented this recipe"
* "Abby sees herself in the lead character" -> "Abby sees Abby in the lead character"
* "Abby keeps a journal to remind herself of past gaming victories" -> "Abby keeps a journal to remind Abby of past gaming victories"

My solution was [to change all the examples so none of them are in the first format](https://github.com/fishpercolator/name.pn/compare/main...pronounless#diff-44438ce218f5287c58d0017f965d888715635d94280669896f75841fbd7b4cd7L33-R46) which feels substandard but the only sensible approach I could think of. Any thoughts from anyone?

A note to myself about things that are not done yet:

- [ ] Unit tests
- [ ] Tests for new functionality
- [ ] Grey out the pronoun checkboxes when a pronounless style is selected
- [ ] Update the API to (a) include the `pronounless_style` and (b) ensure `pronouns` is blank when one of these styles is selected

**Comment by pedantic-git** [comment]
Update from today: it's all working as expected now but there are no functional tests for the new behaviour (except the API) so I am not merging it back until I've had a chance to write these.

**Comment by pedantic-git** [comment]
This is implemented and live now - let me know what you think!
