### ISSUE TITLE
We/ours pronoun option

### ISSUE THREAD

**Issue by EireSeo** [fishpercolator/name.pn#42]
Hello, is it possible to add my preferred pronouns of We/Ours/Us or just We/Us to the pronoun list when signing up? Thanks!

**Comment by pedantic-git** [comment]
Hi @EireSeo - sorry for the late response... I missed this somehow! I've added this to the list of pronouns. Are you able to verify it does what you expect? Is it _ourselves_ or _ourself_ in the reflexive?
