### ISSUE TITLE
it/its pronouns

### ISSUE THREAD

**Issue by merchygoedwig** [fishpercolator/name.pn#45]
Hi! Absolutely love the site - fantastic idea! Would it be possible to add it/its pronouns to the list? A lá:

- Genevieve plays board games
- It is a bit competitive
- Maybe you will win a game against it one day
- Its boardgame collection is impressive
- Your collection is a lot smaller than its
- Genevieve keeps a journal to remind itself of past gaming victories

**Comment by pedantic-git** [comment]
Hi @merchygoedwig - so sorry for the delay responding to this. I had my notification settings wrong and missed it completely (now rectified!)

I've added this pronoun set. Can you let me know it behaves as you'd expect?

One interesting thing is that name.pn always renders the name of a pronoun set in the form nominative/oblique (e.g. they/them) which means for this set it comes out as "it/it". Does this sound right to you? I noticed you used "it/its" in this request (nominative/possessive, for my pronouns it would be "they/theirs") - does this make more sense? I wonder if the rule should be nominative/oblique if they're different and nominative/possessive (or nominative/determiner, e.g. "they/their") if the first two are the same.

**Comment by merchygoedwig** [comment]
Hi! Just changed the settings on my profile and it behaves as expected, thank you so much!

I hadn't realised the nominative/oblique thing myself, I think your suggestion of changing pronoun form as you suggest is a good solution! 'it' pronouns seem to be an outlier in the standard nominative/accusative display form in that they are the same (well, except for neopronouns I imagine), I hadn't realised this myself until you'd mentioned it!

**Comment by pedantic-git** [comment]
Thanks for your thoughts! I'll add that to the backlog.
