### ISSUE TITLE
Nominative/oblique doesn't act right for pronoun sets when they're the same as each other

### ISSUE THREAD

**Issue by pedantic-git** [fishpercolator/name.pn#54]
The pronoun "it" has the same nominative and oblique so it shows up as "it/it".

In this situation we should use a different second pronoun in the name of the pronoun set - maybe the possessive determiner (e.g. it/its). 

h/t @merchygoedwig for the prompt and advice.

**Comment by clarfonthey** [comment]
In general, I prefer specifying pronouns as nominative/oblique/determiner since it helps avoid these ambiguities, particularly when using neopronouns. So, you'd get she/her/her, he/him/his, they/them/their, and it/it/its in these cases.

**Comment by pedantic-git** [comment]
Thanks @clarfonthey - I might make that an option for people who prefer to display their pronouns this way too.

**Comment by pedantic-git** [comment]
@merchygoedwig I've done a simple change for this to say "it/its" (nominative/possessive) when the nominative and oblique are the same, but I'll leave the ticket open because I do think @clarfonthey's suggestion is good too.

**Comment by pedantic-git** [comment]
@clarfonthey And now there's an option to select "pronoun style three" in your profile settings, if you prefer "they/them/theirs". It always uses the _possessive_ (theirs, hers) rather than the _possessive determiner_ (their, her) for this because for all the pronoun sets I have so far this felt the most natural. Let me know what you think!
