### ISSUE TITLE
Sie/hir pronouns?

### ISSUE THREAD

**Issue by DEADORCHESTRA** [fishpercolator/name.pn#79]
Hello! I have recently started using name.pn and really enjoy its comprehensiveness. I use sie/hir pronouns (conjugated identically to the more popular ze/hir, except for the different subject form) and would love to see them included on the list of selectable pronouns. Thanks!

**Comment by pedantic-git** [comment]
Hi @DEADORCHESTRA - thank you so much for this suggestion! You know, I was just thinking about this pronoun set the other day, and wondering if any name.pn users used it. I've added it to the list now - let me know if it works OK for you!
