### ISSUE TITLE
Audio experience is inconsistent across platforms, especially iOS

### ISSUE THREAD

**Issue by pedantic-git** [fishpercolator/name.pn#9]
This is a big one and because I don't have access to modern iOS dev hardware it's proving very tricky to fix.

* Audio recorded not on iOS does not play back on iOS. Probably because of codec incompatibility.
* Audio recorded on iOS only plays back on iOS? Not certain of this one.
* Would converting them all to WAV be the solution? Seems a bit heavyweight on the ol' bandwidth.
* Maybe the correct solution is to transcode so both formats are available? Maybe using a service like transloadit?

Any help or comments below would be gratefully received!

**Comment by wizzwizz4** [comment]
> Would converting them all to WAV be the solution? Seems a bit heavyweight on the ol' bandwidth.

[FLAC is supported on 96.4% of used browsers, according to caniuse.com.](https://caniuse.com/flac). FLAC is basically compressed WAV; you don't _need_ a lossless encoding for representing speech, but if you're considering WAV, please consider FLAC.

**Comment by pedantic-git** [comment]
@wizzwizz4 Thank you for this! As far as I know, browsers don't have built-in functionality for _creating_ FLAC files, like they do for WAV and for some lossy formats. So if I were to use FLAC I'd have to use a transcoding service like transloadit as part of the upload process. I need to think about how I can support that with my meagre running costs but it might well be the only viable solution - if I do switch to a transcoding service I could probably use a pair of lossy formats rather than FLAC but it's worth considering.

**Comment by pedantic-git** [comment]
The latest on this: I've done a complete rewrite of the code (bit messy; needs tidying up) on the [audio-revamp](https://github.com/fishpercolator/name.pn/tree/audio-revamp) branch. I've only got an ancient iPhone and even if I enable the various APIs in experimental settings, I can't get it to record.

I've deployed the code to https://name-pn-qa.herokuapp.com/ and I'd love people - especially those with iOS devices - to give it a test and let me know what works and what doesn't.

I reckon it's still a long way from being stable but it's so challenging without access to a modern iOS device.

**Comment by pedantic-git** [comment]
An update - this is now fully implemented and deployed to the above URL. If anyone can test it for the next week before I merge it back to production I'd be very grateful!

The tests are a bit dodgy because it seems like it's hard to get permissions working properly through chromedp/ferrum (even issuing the commands manually to a headful browser, I see no change!) so I've added a mock permissions parameter that at least allows us to test a few features of the UI, albeit not the recording itself.

**Comment by pedantic-git** [comment]
This has been successfully closed by #92 - feedback is welcome and encouraged!
